name:  Build
on:
  pull_request:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
#      - name: Gradle build
#        run: ./gradlew build
      - name: Generate sarif example
        run: cp integration_tests/example.sarif stackhawk-scan-results.sarif
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: stackhawk-scan-results.sarif
          # Optional category for the results
          # Used to differentiate multiple results for one commit
          category: StackHawk