name: Windows Integration Tests
on:
  workflow_call:
    inputs:
      version:
        description: "Version of HawkScan to use"
        required: true
        type: string
    secrets:
      HAWK_API_KEY:
        description: "API key for running the scans"
        required: true

jobs:
  windows-test:
    runs-on: windows-2022
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          repository: kaakaww/javaspringvulny
          ref: refs/heads/main
      - name: Install HawkScan MSI
        shell: pwsh
        run: msiexec.exe /i https://download.stackhawk.com/hawk/msi/hawk-${{ inputs.version }}.msi INSTALLDIR="${{ github.workspace }}\hawk-${{ inputs.version }}" /passive
      - name: Start javaspringvulny
        shell: pwsh
        run: ./gradlew.bat bootRun --args='--spring.profiles.active=windows' &
      - name: Run HawkScan from MSI
        shell: pwsh
        run: ./hawk-${{ inputs.version }}/hawk.exe scan stackhawk.yml -e APP_ENV=windows-test
